kind = "web"
previewPath = "/"
title = "Kasi Dash"
version = "1.0.0"
id = "artifacts/kasi-dash"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18897

[services.development]
run = "pnpm --filter @workspace/kasi-dash run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/kasi-dash", "run", "build" ]
publicDir = "artifacts/kasi-dash/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18897"
BASE_PATH = "/"
